services:
  mini-web-notepad:
    container_name: mini-web-notepad
    image: reg233/mini-web-notepad:latest
    environment:
      # UPLOAD_MAX_FILESIZE: 20M
      # POST_MAX_SIZE: 21M
      # MAX_EXECUTION_TIME: 90
      # PRIVATE_MODE: "edit"
      # USER_ID: "6678ec58-e7d9-46e7-ae25-b92127ef056e"
      # USERNAME: ""
      # PASSWORD: ""
      # JWT_KEY: "cc63eb9d-cde1-442b-b7b1-5d483f6bf511"
      # HOSTED_ON: ""
      # HOSTED_ON_URL: ""
      NOTES_MAX_SIZE: 1073741824
      NOTE_MAX_LENGTH: 24576
    restart: unless-stopped
    ports:
      - "10000:80"
    volumes:
      - ./_notes:/var/www/html/_notes
